{{- if .Values.config.createAppConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "besvc.fullname" . }}-app-config
  labels:
    {{- include "besvc.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    {{- .Values.config.appSettings | toYaml | nindent 4 }}
{{- end }}
